# Generated by Django 6.0.4 on 2026-04-15 02:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('four_wheeler', 'Four Wheeler')], db_index=True, help_text='Limits a brand to either two wheelers or four wheelers.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='vehicles_br_categor_b32df5_idx'), models.Index(fields=['category', 'created_at'], name='vehicles_br_categor_1b1b25_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('four_wheeler', 'Four Wheeler')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold', 'Sold'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG')], db_index=True, max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], db_index=True, default='manual', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('engine_cc', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('mileage_kmpl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('seating_capacity', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=25)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['category', 'status', '-created_at'], name='vehicles_ve_categor_1c6f15_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['brand', 'category', 'status'], name='vehicles_ve_brand_i_62d31f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['fuel_type', 'status', '-created_at'], name='vehicles_ve_fuel_ty_26776c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['city', 'status', '-created_at'], name='vehicles_ve_city_6d2312_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_featured', 'status', '-created_at'], name='vehicles_ve_is_feat_9fb596_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['created_by', 'status', '-created_at'], name='vehicles_ve_created_c419ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('brand', 'category', 'name', 'year'), name='unique_vehicle_per_brand_category_name_year'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='vehicle_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 1950)), name='vehicle_year_at_least_1950'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('engine_cc__isnull', True), ('engine_cc__gt', 0), _connector='OR'), name='vehicle_engine_cc_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('mileage_kmpl__isnull', True), ('mileage_kmpl__gte', 0), _connector='OR'), name='vehicle_mileage_non_negative_or_null'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('seating_capacity__isnull', True), ('seating_capacity__gte', 1), _connector='OR'), name='vehicle_seating_capacity_positive_or_null'),
        ),
        migrations.AddIndex(
            model_name='vehicleimage',
            index=models.Index(fields=['vehicle', 'is_primary', 'sort_order'], name='vehicles_ve_vehicle_2b6137_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleimage',
            constraint=models.UniqueConstraint(fields=('vehicle', 'sort_order'), name='unique_vehicle_image_sort_order'),
        ),
        migrations.AddConstraint(
            model_name='vehicleimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('vehicle',), name='unique_primary_image_per_vehicle'),
        ),
        migrations.AddIndex(
            model_name='vehicleinquiry',
            index=models.Index(fields=['vehicle', 'status', '-created_at'], name='vehicles_ve_vehicle_fc5daf_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinquiry',
            index=models.Index(fields=['email', 'status', '-created_at'], name='vehicles_ve_email_8724a0_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinquiry',
            index=models.Index(fields=['status', '-created_at'], name='vehicles_ve_status_e69b25_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleinquiry',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='vehicle_inquiry_email_not_blank'),
        ),
    ]
