# Generated by Django 6.0.4 on 2026-04-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_image_fields_and_inquiry_metadata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vehicleinquiry',
            new_name='vehicles_ve_dealer__6f6150_idx',
            old_name='vehicles_ve_dealer__2b5056_idx',
        ),
    ]
