# Generated by Django 6.0.4 on 2026-04-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_rename_vehicles_ve_dealer__2b5056_idx_vehicles_ve_dealer__6f6150_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(db_index=True, max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=25)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['dealer_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='vehicleimage',
            index=models.Index(fields=['vehicle', 'color', 'sort_order'], name='vehicles_ve_vehicle_10d829_idx'),
        ),
        migrations.AddField(
            model_name='authorizeddealer',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_dealers', to='vehicles.brand'),
        ),
        migrations.AddIndex(
            model_name='authorizeddealer',
            index=models.Index(fields=['brand', 'city'], name='vehicles_au_brand_i_7302eb_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizeddealer',
            index=models.Index(fields=['brand', '-created_at'], name='vehicles_au_brand_i_547fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizeddealer',
            index=models.Index(fields=['city', 'dealer_name'], name='vehicles_au_city_0292f6_idx'),
        ),
    ]
